{{
  config(
    materialized = 'table',
    labels = {'type': 'mongodb', 'contains_pie': 'no', 'category':'source'}  
   )
}}

/* Tous les abonnements dont le starting_at sont null sont des abonnements annulés */
select 
  _id as id,
  stripe_id,
  price,
  place._id as place_id,
  place.closing.reason as place_closing_reason,
  place.closing.FROM as place_closing_from,
  place.closing.to as place_closing_to,  
  place.name as place_name,
  place.createdat as place_createdat,
  place.updatedat as place_updatedat,
  place.lat as place_lat,
  place.lng as place_lng,  
  place.opening.schedule as place_opening_schedule,
  place.opening.day as place_opening_days,
  place.opening.extra as place_opening_extra,
  place.description as place_description,   
  formula,
  _sdc_batched_at,
  _sdc_extracted_at,
  nedb_id,
  allergies.oysters AS allergies_oysters,
  allergies.crustaceans AS allergies_crustaceans,
  allergies.shells AS allergies_shells,
  allergies.fishes AS allergies_fishes,
  allergies.others AS allergies_others,
  allergies.invalid AS allergies_invalid,
  _sdc_sequence,
  _sdc_received_at,
  startingat,
  late.lastingat,
  late.place.lng,
  late.place.name as late_place_name,
  late.place.createdat as late_place_createdat,
  late.place.updatedat as late_place_updatedat,
  late.place._id as late_place_id, 
  updatedat,
  quantity,
  rate,
  createdat,
  _sdc_table_version,
  user.firstname as user_firstname,
  user.lastname as user_lastname,
  user.anonymous as user_anonymous,
  user.phone as user_phone,
  user._id as user_id,
  user.email as user_email,
  freedelivery,
  subscribed,
  upcoming.status AS upcoming_status,
  upcoming.deposit.place._id as deposit_place_id,
  upcoming.deposit.deliveryat AS upcoming_deposit_deliveryat,
  upcoming.deposit.code.delivery AS upcoming_deposit_code_delivery,
  upcoming.deposit.code.collecting AS upcoming_deposit_code_collecting,
  upcoming.deposit.reference AS upcoming_deposit_reference,
  coupon
  from {{ source('mongodb', 'subscription') }}
order by id asc 

