{{
  config(
    materialized = 'table',
    labels = {'type': 'stripe', 'contains_pie': 'yes', 'category':'source'}  
   )
}}

SELECT
object,
invoice_item,
invoice,
currency,
discountable,
id,
_sdc_table_version,
quantity,
subscription,
metadata.date AS metadata_date,		
metadata.subscription AS metadata_subscription	,
metadata.refunded AS metadata_refunded,
proration,
_sdc_received_at,
_sdc_sequence,
subscription_item,
-- discount_amounts,
livemode,
type,
amount,
plan.object AS	plan_object		,
plan.created AS		plan_created,
plan.currency AS	plan_currency,
plan.id AS	plan_id,
plan.usage_type AS		plan_usage_type	,
plan.product	 AS		plan_product,
plan.interval AS	plan_interval,
plan.interval_count AS	plan_interval_count,
plan.amount_decimal AS	plan_amount_decimal,
plan.livemode AS		plan_livemode,
plan.amount AS		plan_amount,
plan.billing_scheme AS 	plan_billing_scheme,
plan.active AS		plan_active,
plan.name AS plan_name,
period.start AS period_start,
period.end AS period_end,
price.object AS price_object,
price.created AS price_created,
price.tax_behavior AS price_tax_behavior,
price.currency AS price_currency,
price.id AS price_id,
price.product AS price_product,
price.recurring.interval_count AS price_recurring_interval_count,
price.recurring.usage_type AS price_recurring_usage_type,
price.recurring.interval AS price_recurring_interval,
price.unit_amount_decimal AS price_unit_amount_decimal,
price.livemode AS price_livemode,
price.type AS price_type,
price.billing_scheme AS price_billing_scheme,
price.unit_amount AS price_unit_amount,
price.active AS price_active,
_sdc_batched_at,
_sdc_extracted_at,
description,
-- proration_details
FROM  {{ source('stripe', 'invoice_line_items') }}
